version = 0.1
[default.deploy.parameters]
stack_name = "serverless-testing"
resolve_s3 = true
s3_prefix = "serverless-testing"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
